### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by loftusa** [iitzco/deepbrain#3]
Setup:

`pip install deepbrain`
`from deepbrain import Extractor`

Error:
```
ImportError                               Traceback (most recent call last)
 in 
      5 
      6 import nibabel as nib
----> 7 from deepbrain import Extractor

/usr/local/Caskroom/miniconda/base/envs/ndmg/lib/python3.6/site-packages/deepbrain/__init__.py in 
----> 1 from deepbrain.extractor import Extractor

/usr/local/Caskroom/miniconda/base/envs/ndmg/lib/python3.6/site-packages/deepbrain/extractor.py in 
      1 import tensorflow as tf
      2 import numpy as np
----> 3 from skimage.transform import resize
      4 import os
      5 

/usr/local/Caskroom/miniconda/base/envs/ndmg/lib/python3.6/site-packages/skimage/__init__.py in 
    156     except ImportError as e:
    157         _raise_build_error(e)
--> 158     from .util.dtype import *
    159 
    160 

/usr/local/Caskroom/miniconda/base/envs/ndmg/lib/python3.6/site-packages/skimage/util/__init__.py in 
      5 from .apply_parallel import apply_parallel
      6 
----> 7 from .arraycrop import crop
      8 from ._regular_grid import regular_grid, regular_seeds
      9 from .unique import unique_rows

/usr/local/Caskroom/miniconda/base/envs/ndmg/lib/python3.6/site-packages/skimage/util/arraycrop.py in 
      6 
      7 import numpy as np
----> 8 from numpy.lib.arraypad import _validate_lengths
      9 
     10 

ImportError: cannot import name '_validate_lengths'
```

**Comment by loftusa** [comment]
Fixed by grabbing `scikit-image` with a `conda install` command, looks like a scikit-image dependency thing

**Comment by lucahei** [comment]
I have the same issue, how exactly did you grab scikit-image with a conda install command? I tried to do the following: 

`conda install -c conda-forge scikit-image`

But I'm still getting the same error message.
